# File: wrangler.toml

name = "web-buku-project"
compatibility_date = "2024-05-01"

# Beri tahu wrangler di mana skrip utamanya
main = "bulk-insert.js"

# Ini adalah binding database Anda, sudah benar
[[d1_databases]]
binding = "DB" # Nama ini (DB) HARUS SAMA dengan di skrip .js (env.DB)
database_name = "database-buku"
database_id = "b93d0016-2364-4aa3-9ec9-e0e17911af2c" # ID Anda dari error log
